version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y awscli
  pre_build:
    commands:
      - mkdir -p $HOME/.m2
      - aws s3 cp s3://com.sigpwned.build/configuration/java/maven/settings.xml $HOME/.m2
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/jsonification-3.0.5.jar
    - target/jsonification-3.0.5-sources.jar
    - target/jsonification-3.0.5-javadoc.jar